begin;

alter table if exists public.clientes
  add column if not exists tipo_cliente text default 'cliente',
  add column if not exists credito_habilitado boolean default false,
  add column if not exists notas text default '';

alter table if exists public.ventas
  add column if not exists cliente_id bigint,
  add column if not exists cliente_nombre text,
  add column if not exists tipo_precio text default 'cliente',
  add column if not exists es_credito_plaza boolean default false;

create table if not exists public.cuentas_plaza_movimientos (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null,
  cliente_nombre text not null,
  tipo text not null check (tipo in ('cargo','abono','ajuste')),
  monto numeric(12,2) not null check (monto >= 0),
  items jsonb not null default '[]'::jsonb,
  venta_id bigint,
  nota text default '',
  usuario text default 'Sistema',
  fecha timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists idx_cuenta_plaza_cliente_fecha
  on public.cuentas_plaza_movimientos (cliente_id, fecha desc);

alter table public.cuentas_plaza_movimientos enable row level security;

drop policy if exists "Acceso publico a cuentas plaza" on public.cuentas_plaza_movimientos;
create policy "Acceso publico a cuentas plaza"
  on public.cuentas_plaza_movimientos
  for all
  to public
  using (true)
  with check (true);

commit;;
