-- LOTO GAMES ERP / POS V1
-- Esquema final idempotente para instalaciones nuevas o bases antiguas.
-- Esta migración agrega estructura; NO aplica el +5% masivo a productos existentes.
-- Para transformar precios existentes usar 20260818_productos_markup5.sql después de respaldo.

begin;

-- PRODUCTOS
alter table if exists public.productos
  add column if not exists precio_cliente numeric(12,2),
  add column if not exists precio_mayorista numeric(12,2),
  add column if not exists precio_plaza numeric(12,2),
  add column if not exists precio_base_cliente numeric(12,2),
  add column if not exists precio_base_mayorista numeric(12,2),
  add column if not exists precio_base_plaza numeric(12,2),
  add column if not exists precio_markup_5_aplicado boolean not null default false;

update public.productos
set
  precio_cliente = coalesce(precio_cliente, precio, 0),
  precio_mayorista = coalesce(precio_mayorista, precio_cliente, precio, 0),
  precio_plaza = coalesce(precio_plaza, precio_cliente, precio, 0),
  precio_base_cliente = coalesce(precio_base_cliente, precio_cliente, precio, 0),
  precio_base_mayorista = coalesce(precio_base_mayorista, precio_mayorista, precio_cliente, precio, 0),
  precio_base_plaza = coalesce(precio_base_plaza, precio_plaza, precio_cliente, precio, 0)
where precio_cliente is null
   or precio_mayorista is null
   or precio_plaza is null
   or precio_base_cliente is null
   or precio_base_mayorista is null
   or precio_base_plaza is null;

-- CLIENTES / LOCATARIOS
alter table if exists public.clientes
  add column if not exists tipo_cliente text default 'cliente',
  add column if not exists credito_habilitado boolean default false,
  add column if not exists notas text default '';

-- VENTAS
alter table if exists public.ventas
  add column if not exists cliente_id bigint,
  add column if not exists cliente_nombre text,
  add column if not exists tipo_precio text default 'cliente',
  add column if not exists es_credito_plaza boolean default false,
  add column if not exists descuento_porcentaje numeric(5,2) default 0,
  add column if not exists descuento_monto numeric(12,2) default 0;

update public.ventas
set
  subtotal = coalesce(subtotal, total),
  descuento_porcentaje = coalesce(descuento_porcentaje, 0),
  descuento_monto = coalesce(descuento_monto, 0)
where subtotal is null
   or descuento_porcentaje is null
   or descuento_monto is null;

-- CUENTA CORRIENTE DE PLAZA
create table if not exists public.cuentas_plaza_movimientos (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null,
  cliente_nombre text not null,
  tipo text not null check (tipo in ('cargo','abono','ajuste')),
  monto numeric(12,2) not null check (monto >= 0),
  items jsonb not null default '[]'::jsonb,
  venta_id bigint,
  nota text default '',
  usuario text default 'Sistema',
  fecha timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists idx_cuenta_plaza_cliente_fecha
  on public.cuentas_plaza_movimientos (cliente_id, fecha desc);

-- USUARIOS
alter table if exists public.usuarios
  add column if not exists password_hash text,
  add column if not exists password_salt text,
  add column if not exists pin_hash text,
  add column if not exists pin_salt text,
  add column if not exists privilegios jsonb default '[]'::jsonb,
  add column if not exists estado text default 'activo';

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema='public' and table_name='usuarios' and column_name='password'
  ) then
    execute 'alter table public.usuarios alter column password drop not null';
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema='public' and table_name='usuarios' and column_name='pin'
  ) then
    execute 'alter table public.usuarios alter column pin drop not null';
  end if;
end $$;

create unique index if not exists idx_usuarios_email_lower
  on public.usuarios (lower(email));

-- TRASPASOS
alter table if exists public.traspasos
  add column if not exists producto_sku text,
  add column if not exists origen text,
  add column if not exists destino text,
  add column if not exists estado text default 'completado',
  add column if not exists created_at timestamptz default now();

update public.traspasos
set
  origen = coalesce(origen, local_origen),
  destino = coalesce(destino, local_destino),
  estado = coalesce(estado, 'completado'),
  created_at = coalesce(created_at, fecha, now())
where origen is null
   or destino is null
   or estado is null
   or created_at is null;

commit;

-- Seguridad:
-- No crear políticas RLS públicas nuevas aquí. El endurecimiento de autorización
-- debe hacerse junto con el mecanismo de autenticación de producción para no
-- dejar el frontend sin acceso legítimo ni exponer escrituras anónimas.
