-- LOTO GAMES POS - Finalization migration
-- Safe, additive migration. Run once in Supabase SQL Editor before enabling the v2 modules.

begin;

-- ============================================================
-- PRODUCTOS: tres precios explícitos
-- ============================================================
alter table if exists public.productos
  add column if not exists precio_cliente numeric(12,2),
  add column if not exists precio_mayorista numeric(12,2),
  add column if not exists precio_plaza numeric(12,2);

update public.productos
set
  precio_cliente   = coalesce(precio_cliente, precio, 0),
  precio_mayorista = coalesce(precio_mayorista, precio, 0),
  precio_plaza     = coalesce(precio_plaza, precio, 0)
where precio_cliente is null
   or precio_mayorista is null
   or precio_plaza is null;

-- ============================================================
-- CLIENTES: clasificación y crédito de plaza
-- ============================================================
alter table if exists public.clientes
  add column if not exists tipo_cliente text default 'cliente',
  add column if not exists credito_habilitado boolean default false,
  add column if not exists notas text default '';

-- ============================================================
-- VENTAS: conservar comprador y lista de precio utilizada
-- ============================================================
alter table if exists public.ventas
  add column if not exists cliente_id bigint,
  add column if not exists cliente_nombre text,
  add column if not exists tipo_precio text default 'cliente',
  add column if not exists es_credito_plaza boolean default false;

-- ============================================================
-- CUENTA CORRIENTE DE LOCATARIOS / VENTA A PLAZA
-- Cargos = mercancía entregada. Abonos = pagos recibidos.
-- El saldo se calcula a partir de movimientos, no se duplica.
-- ============================================================
create table if not exists public.cuentas_plaza_movimientos (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null,
  cliente_nombre text not null,
  tipo text not null check (tipo in ('cargo','abono','ajuste')),
  monto numeric(12,2) not null check (monto >= 0),
  items jsonb not null default '[]'::jsonb,
  venta_id bigint,
  nota text default '',
  usuario text default 'Sistema',
  fecha timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists idx_cuenta_plaza_cliente_fecha
  on public.cuentas_plaza_movimientos (cliente_id, fecha desc);

-- ============================================================
-- USUARIOS: credenciales derivadas, nunca nuevas contraseñas planas
-- Las columnas password/pin antiguas pueden permanecer temporalmente
-- para migración; los módulos v2 dejan de crearlas.
-- ============================================================
alter table if exists public.usuarios
  add column if not exists password_hash text,
  add column if not exists password_salt text,
  add column if not exists pin_hash text,
  add column if not exists pin_salt text,
  add column if not exists privilegios jsonb default '[]'::jsonb,
  add column if not exists estado text default 'activo';

create unique index if not exists idx_usuarios_email_lower
  on public.usuarios (lower(email));

-- ============================================================
-- TRASPASOS: normalizar los campos que usan módulo y reportes
-- ============================================================
alter table if exists public.traspasos
  add column if not exists producto_sku text,
  add column if not exists origen text,
  add column if not exists destino text,
  add column if not exists estado text default 'completado',
  add column if not exists created_at timestamptz default now();

-- Compatibilidad con registros escritos por versiones anteriores.
update public.traspasos
set
  origen = coalesce(origen, local_origen),
  destino = coalesce(destino, local_destino),
  tipo = coalesce(tipo, 'traspaso'),
  estado = coalesce(estado, 'completado'),
  created_at = coalesce(created_at, fecha, now())
where origen is null
   or destino is null
   or tipo is null
   or estado is null
   or created_at is null;

commit;

-- IMPORTANTE:
-- La anon key de Supabase es pública por diseño. Antes de exponer el POS a Internet,
-- revisar y activar RLS/policies para productos, ventas, usuarios, clientes,
-- cuentas_plaza_movimientos y traspasos. La autenticación de aplicación por sí sola
-- no sustituye autorización a nivel de base de datos.
